[package]
name = "wasm2casm"
version = "0.1.0"
edition = "2024"

[dependencies]
cairo-m-common = { git = "https://github.com/kkrt-labs/cairo-m.git" }
cairo-m-compiler-codegen = { git = "https://github.com/kkrt-labs/cairo-m.git" }
wasmparser = "0.235.0"
